import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,access,mkdir,writeFile,rm} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {Model,STEP,W,H} from '../course/assets/model.js';
import {lessons} from '../course/assets/lessons.js';
import {calculate,verify} from '../course/assets/exercises.js';
for(const lesson of lessons){
 test(`lesson ${lesson.id}: solution, wrong code and placeholder`,()=>{assert(verify(lesson,lesson.solution).every(r=>r.pass));assert(!verify(lesson,`${lesson.solution.split('=')[0]} = 123456`).every(r=>r.pass));assert.throws(()=>verify(lesson,lesson.starter));});
 test(`scene ${lesson.id}: stable defaults and extreme allowed parameters`,()=>{for(const extreme of [false,true]){const m=new Model(lesson.id);if(extreme)Object.assign(m.params,{gravity:600,restitution:1,damping:0,stiffness:100,field:600,power:6});if([10,14].includes(lesson.id))m.launch(0,{x:20,y:380},{x:120,y:300});for(let i=0;i<2400;i++)m.step(STEP);for(const b of m.balls){assert(Number.isFinite(b.x+b.y+b.vx+b.vy));assert(b.x>=b.r&&b.x<=W-b.r);assert(b.y>=b.r&&b.y<=H-b.r);}}});
}
test('parser obeys precedence, sign, division and rejects executable input',()=>{assert.equal(calculate('x = (a + 2) * -3;', {a:4},'x'),-18);assert.equal(calculate('x = 8 / 2 + 1',{},'x'),5);for(const src of ['x=window.location','x=alert(1)','x=1; fetch(1)','x=Infinity','x=1/0','x=2**3','x=__proto__','x=1,2'])assert.throws(()=>calculate(src,{},'x'));});
test('gravity is time based and semi-implicit',()=>{const m=new Model(5);m.params.damping=0;m.params.gravity=300;m.balls[0].y=30;for(let i=0;i<120;i++)m.step();assert(Math.abs(m.balls[0].vy-300)<1e-8);assert(Math.abs(m.balls[0].y-181.25)<1e-7);});
test('collision conserves equal-mass momentum when restitution=1',()=>{const m=new Model(7);m.params.gravity=0;m.params.damping=0;m.params.restitution=1;m.balls=[m.ball(100,100),m.ball(131,100)];m.balls[0].vx=100;m.step();assert(Math.abs(m.balls[0].vx)<1e-8);assert(Math.abs(m.balls[1].vx-100)<1e-8);});
test('rigid link length and fixed anchor',()=>{const m=new Model(9);for(let i=0;i<1200;i++)m.step();assert.equal(m.balls[0].x,400);assert.equal(m.balls[0].y,60);for(const l of m.links.filter(l=>l.type==='rigid')){const a=m.balls[l.a],b=m.balls[l.b];assert(Math.abs(Math.hypot(b.x-a.x,b.y-a.y)-l.length)<1);}});
test('circuit opens; increasing R reduces current',()=>{const m=new Model(11);assert.equal(m.current(),.05);m.params.resistance=200;assert.equal(m.current(),.025);m.closed=false;assert.equal(m.current(),0);});
test('link creation and duplicate rejection',()=>{const m=new Model(14);assert(m.addLink(0,1));assert(!m.addLink(1,0));assert(!m.addLink(0,0));});
test('game scores in complete scene with network, once per shot',()=>{const m=new Model(14);const b=m.balls[0];m.launch(0,{x:b.x-100,y:b.y+120},{x:b.x,y:b.y});for(let i=0;i<1500;i++)m.step();assert.equal(m.score,1);assert.equal(m.shots,1);});
test('static build: all relative resources, navigation and direct lesson URLs resolve under /js/',async()=>{execFileSync('node',['scripts/build.mjs']);const pages=['dist/js/index.html',...lessons.map(l=>`dist/js/lessons/${l.slug}/index.html`)];for(const file of pages){const content=await readFile(file,'utf8');assert(content.includes('lang="ru"'));for(const [,url] of content.matchAll(/(?:href|src)="([^"]+)"/g)){if(url.startsWith('https:')||url.startsWith('#'))continue;const resolved=new URL(url,new URL(file.replace('dist',''), 'https://qper.org'));assert(resolved.pathname.startsWith('/js/'));let path='dist'+resolved.pathname;if(path.endsWith('/'))path+='index.html';await access(path);}if(file.includes('/lessons/'))assert(content.includes('id="solution" hidden'));}});
test('build preserves root files and CNAME',async()=>{const dir='/tmp/physics-pages-test';await mkdir(dir,{recursive:true});await writeFile(dir+'/CNAME','qper.org');await writeFile(dir+'/index.html','existing site');execFileSync('node',['scripts/build.mjs'],{env:{...process.env,PAGES_DIR:dir}});assert.equal(await readFile(dir+'/index.html','utf8'),'existing site');assert.equal(await readFile(dir+'/CNAME','utf8'),'qper.org');await rm(dir,{recursive:true,force:true});});
